"""Add message metadata fields

Revision ID: cc503065a20e
Revises: 3be00d88c22b
Create Date: 2026-03-03 08:29:51.975586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc503065a20e'
down_revision: Union[str, None] = '3be00d88c22b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('token_count', sa.Integer(), nullable=True))
    op.add_column('chat_messages', sa.Column('finish_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'finish_reason')
    op.drop_column('chat_messages', 'token_count')
    # ### end Alembic commands ###
